name: Deploy Quasar SPA to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build

  report-build-status:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Report build status
        run: echo "✅ Build completed successfully!"

  deploy:
    runs-on: ubuntu-latest
    needs: build   # ต่อกับ build โดยตรง
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist



